RUN_STRINGS = (
    "Now you see me, now you don't." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Huh? what? did they get away?",
    "Get back here!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb ",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

SLAP_Sukuna_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Don't again dare to slap me ||A-S-S-H-0-L-E||.",
)

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \\(˚˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
    "{user2} was shot by {user1}.",
    "{user2} walked into a cactus while trying to escape {user1}.",
    "{user2} drowned whilst trying to escape {user1}.",
    "{user2} fell into a patch of cacti.",
    "{user2} went up in flames.",
    "{user2} burned to death.",
    "{user2} was burnt to a crisp whilst fighting {user1}.",
    "{user2} was struck by lightning.",
    "{user2} was slain by {user1}.",
    "{user2} was killed by magic.",
    "{user2} starved to death.",
    "{user2} fell out of the world.",
    "{user2} was knocked into the void by {user1}.",
    "{user2}'s bones are scraped clean by the desolate wind.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} says goodbye to this cruel world.",
    "{user2} got rekt.",
    "{user2} was sawn in half by {user1}.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2}'s death put another notch in {user1}'s axe.",
    "{user2} died from {user1}'s mysterious tropical disease.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user2} was shot before being thrown out of a plane.",
    "{user2} has encountered an error.",
    "{user2} died and reincarnated as a goat.",
    "{user1} threw {user2} off a building.",
    "{user2} got a premature burial.",
    "{user1} spammed {user2}'s email.",
    "{user1} hit {user2} with a small, interstellar spaceship.",
    "{user1} put {user2} in check-mate.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} died of hospital gangrene.",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} checkmated {user2} in two moves.",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!.",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    r"( う-´)づ︻╦̵̵̿╤── \(˚˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2}, to infinity and beyond."
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} exchanged {user2}'s life-force for a cup of chocolate.",
    "{user2} did a 69 with a cactus.",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user1} traveled to the future and spat on {user2}'s grave.",
    "{user2} died from talk-no-jutsu.",
    "{user2} was placed as a carpet for a stomp dance competition.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "{user1} learned why being a crocodile dentist was a bad idea.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
    "angry bird",
    "your ego",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = ("hits", "whacks", "slaps", "smacks", "bashes", "pats")

REACTIONS = (
    "( ͡° ͜ʖ ͡°)",
    "( . •́ _ʖ •̀ .)",
    "( ಠ ͜ʖ ಠ)",
    "( ͡ ͜ʖ ͡ )",
    "(ʘ ͜ʖ ʘ)",
    "ヾ(´〇`)ﾉ",
    "ヽ(o´∀`)ﾉ",
    "((dωb))",
    "└(＾＾)┐",
    "(￣▽￣)/•*¨*•.¸¸",
    "ヾ(■_■)ノ",
    "乁( • ω •乁)",
    "◖(● o ●)◗",
    "(っ˘ڡ˘ς)",
    "( ˘▽˘)っ",
    "(　・ω・)⊃-[二二]",
    "(*´ー`)旦 旦(￣ω￣*)",
    "( ￣▽￣)[] [](≧▽≦ )",
    "(*￣▽￣)旦 且(´∀`*)",
    "(ノ ˘_˘)ノ　ζ|||ζ　ζ|||ζ　ζ|||ζ",
    "(ノ°∀°)ノ･*:.｡. .｡.:*･゜ﾟ･*",
    "(⊃｡•́‿•̀｡)⊃━",
    "(∩` ﾛ ´)⊃━炎炎炎炎炎",
    "( ・∀・)・・・--------",
    "( -ω-)／占~~~~~",
    "○∞∞∞∞ヽ(^ー^ )",
    "(*＾＾)/~~~~~~~~~~◎",
    "((( ￣□)_／",
    "(ﾒ￣▽￣)︻┳═一",
    "ヽ( ･∀･)ﾉ_θ彡Σ(ノ `Д´)ノ",
    "(*`0´)θ(メ°皿°)ﾉ",
    "(; -_-)――――――C<―_-)",
    "ヽ(>_<ヽ) ―⊂|=0ヘ(^‿^ )",
    "(҂` ﾛ ´)︻デ═一 ＼(º □ º l|l)/",
    "/( .□.)＼ ︵╰(°益°)╯︵ /(.□. /)",
    "(`*)O-(`´Q)",
    "(っ•﹏•)っ ==≡눈٩(`皿´҂)ง",
    "ヾ(・ω・)メ(・ω・)ノ",
    "(*^ω^)八(▽)八(-‿‿- )ヽ",
    "ヽ( ω)人(=^‥^= )ﾉ",
    "｡*:(・ω・人・ω・)｡:゜｡",
    "(°(°ω(°ω°(ω)°ω°)ω°)°)",
    "(っ˘▽˘)(˘▽˘)˘▽˘ς)",
    "(*＾ω＾)人(＾ω＾*)",
    r"＼(▽￣ \ (￣▽￣) / ￣▽)／",
    "(￣Θ￣)",
    "＼( ˋ Θ ´ )／",
    "( ´(00)ˋ )",
    "＼(￣(oo)￣)／",
    "／(≧ x ≦)＼",
    "／(=･ x ･=)＼",
    "(=^･ω･^=)",
    "(= ; ｪ ; =)",
    "(=‿‿=)",
    "(＾• ω •＾)",
    "ଲ(ⓛ ω ⓛ)ଲ",
    "ଲ(ⓛ ω ⓛ)ଲ",
    "(^◔ᴥ◔^)",
    "[(－－)]..zzZ",
    "(￣o￣) zzZZzzZZ",
    "(＿ ＿*) Z z z",
    "ﾐ(o*･ω･)ﾉ",
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "ε===(っ≧ω≦)っ",
    "__φ(．．)",
    "ヾ( `ー´)シφ__",
    "( ^▽^)ψ__",
    "|･ω･)",
    "|д･)",
    "┬┴┬┴┤･ω･)ﾉ",
    "|･д･)ﾉ",
    "(*￣ii￣)",
    "(＾〃＾)",
    "m(_ _)m",
    "人(_ _*)",
    "(シ. .)シ",
    "(^_~)",
    "(>ω^)",
    "(^_<)〜",
    "(^_<)",
    "(づ￣ ³￣)づ",
    "(⊃｡•́‿•̀｡)⊃",
    "⊂(´• ω •`⊂)",
    "(*・ω・)ﾉ",
    "(^-^*)/",
    "ヾ(*'▽'*)",
    "(^０^)ノ",
    "(*°ｰ°)ﾉ",
    "(￣ω￣)/",
    "(≧▽≦)/",
    "w(°ｏ°)w",
    "(⊙_⊙)",
    "(°ロ°) !",
    "∑(O_O;)",
    "(￢_￢)",
    "(¬_¬ )",
    "(↼_↼)",
    "(￣ω￣;)",
    "┐('～`;)┌",
    "(・_・;)",
    "(＠_＠)",
    "(•ิ_•ิ)?",
    "ヽ(ー_ー )ノ",
    "┐(￣ヘ￣)┌",
    "┐(￣～￣)┌",
    "┐( ´ д ` )┌",
    "╮(︶▽︶)╭",
    "ᕕ( ᐛ )ᕗ",
    "(ノωヽ)",
    "(″ロ゛)",
    "(/ω＼)",
    "(((＞＜)))",
    "~(>_<~)",
    "(×_×)",
    "(×﹏×)",
    "(ノ_<。)",
    "(μ_μ)",
    "o(TヘTo)",
    "( ﾟ，_ゝ｀)",
    "( ╥ω╥ )",
    "(／ˍ・、)",
    "(つω`｡)",
    "(T_T)",
    "o(〒﹏〒)o",
    "(＃`Д´)",
    "(・`ω´・)",
    "( `ε´ )",
    "(ﾒ` ﾛ ´)",
    "Σ(▼□▼メ)",
    "(҂ `з´ )",
    "٩(╬ʘ益ʘ╬)۶",
    "↑_(ΦwΦ)Ψ",
    "(ﾉಥ益ಥ)ﾉ",
    "(＃＞＜)",
    "(；￣Д￣)",
    "(￢_￢;)",
    "(＾＾＃)",
    "(￣︿￣)",
    "ヾ( ￣O￣)ツ",
    "(ᗒᗣᗕ)՞",
    "(ノ_<。)ヾ(´ ▽ ` )",
    "ヽ(￣ω￣(。。 )ゝ",
    "(ﾉ_；)ヾ(´ ∀ ` )",
    "(´-ω-`( _ _ )",
    "(_;)",
    "(*/_＼)",
    "( ◡‿◡ *)",
    "(//ω//)",
    "(￣▽￣*)ゞ",
    "(„ಡωಡ„)",
    "(ﾉ´ з `)ノ",
    "(-_-)",
    "(─‿‿─)",
    "(´ ω `)",
    "(ღ˘˘ღ)",
    "(´• ω •`) ",
    "╰(*´︶`*)╯",
    "(≧◡≦) ",
    " (˘▽˘>ԅ( ˘˘)",
    "σ(≧ε≦σ) ",
    "(˘∀˘)/(μ‿μ) ",
    "Σ>―(〃°ω°〃)→",
    "(* ^ ω ^)",
    "(o^▽^o)",
    "ヽ(・∀・)ﾉ",
    "(o･ω･o)",
    "(^人^)",
    "( ´ ω ` )",
    "(´• ω •`)",
    "╰(▔∀▔)╯",
    "(◡)",
    "(‿)",
    "(*°▽°*)",
    "(´｡• ᵕ •｡`)",
    "ヽ(>∀<)ノ",
    "＼(￣▽￣)／",
    "(o˘◡˘o)",
    "(╯▽)╯",
    "( ‾́ ◡ ‾́ )",
    "(๑˘︶˘๑)",
    "(´･ᴗ･ ` )",
    "( ͡° ʖ̯ ͡°)",
    "( ఠ ͟ʖ ఠ)",
    "( ಥ ʖ̯ ಥ)",
    "(≖ ͜ʖ≖)",
    "ヘ(￣ω￣ヘ)",
    "(ﾉ≧∀≦)ﾉ",
    "└(￣-￣└))",
    "┌(＾＾)┘",
    "(^_^)",
    "(〜￣△￣)〜",
    "(｢• ω •)｢",
    "( ˘ ɜ˘) ",
    "( o˘◡˘o) ┌iii┐",
    "o(>_<)o",
    "( ・・)つ―{}@{}@{}-",
    "(*´з`)口ﾟ｡ﾟ口(・∀・ )",
    "( *^^)o∀*∀o(^^* )",
    "-●●●-ｃ(・・ )",
    "(ﾉ≧∀≦)ﾉ ‥…━━━",
    "╰( ͡° ͜ʖ ͡° )つ──*:・ﾟ",
    "(∩ᄑ_ᄑ)⊃━ﾟ*･｡*･:≡( ε:)",
    "OwO",
)

TOSS = (
    "Heads",
    "Tails",
)


DECIDE = ("Yes.", "No.", "Maybe.", "Who the hell cares?", "No one give a damn about it")

INSULT_STRINGS = [
    "`Owww ... Such a stupid idiot.`",
    "`Don't drink and type.`",
    "`Command not found. Just like your brain.`",
    "`Bot rule 544 section 9 prevents me from replying to stupid humans like you.`",
    "`Sorry, we do not sell brains.`",
    "`Believe me you are not normal.`",
    "`I bet your brain feels as good as new, seeing that you never use it.`",
    "`If I wanted to kill myself I'd climb your ego and jump to your IQ.`",
    "`You didn't evolve from apes, they evolved from you.`",
    "`What language are you speaking? Cause it sounds like bullshit.`",
    "`You are proof that evolution CAN go in reverse.`",
    "`I would ask you how old you are but I know you can't count that high.`",
    "`As an outsider, what do you think of the human race?`",
    "`Ordinarily people live and learn. You just live.`",
    "`Keep talking, someday you'll say something intelligent!`.......||I doubt it though||",
    "`Everyone has the right to be stupid but you are abusing the privilege.`",
    "`I'm sorry I hurt your feelings when I called you stupid. I thought you already knew that.`",
    "`You should try tasting cyanide.`",
    "`You should try sleeping forever.`",
    "`Pick up a gun and shoot yourself.`",
    "`Try bathing with Hydrochloric Acid instead of water.`",
    "`Go Green! Stop inhaling Oxygen.`",
    "`God was searching for you. You should leave to meet him.`",
    "`You should Volunteer for target in an firing range.`",
    "`Try playing catch and throw with RDX its fun.`",
    "`People like you are the reason we have middle fingers.`",
    "`When your mom dropped you off at the school, she got a ticket for littering.`",
    "`You’re so ugly that when you cry, the tears roll down the back of your head…just to avoid your face.`",
    "`If you’re talking behind my back then you’re in a perfect position to kiss my ||A-S-S||!.`",
    "`Awww! how cute.....me not you`",
    "`You are so ugly that if one direction sees you, they will change their direction to another...`",
    "`You left your brain to God go and take it...`",
    "`If you think you are an idiot..............then you are absolutely right...`",
]


BAN_GIFS = [
    "https://envs.sh/Lwu.mp4",
    "https://envs.sh/5Y9.mp4",
    "https://envs.sh/5Cz.mp4",
]


KICK_GIFS = [
    "https://envs.sh/5C3.mp4",
    "https://envs.sh/5Y9.mp4",
    "https://envs.sh/5CY.mp4",
]


MUTE_GIFS = [
    "https://envs.sh/5CC.mp4",
    "https://envs.sh/5CY.mp4",
]

NOWYES = [
    """
YES          YES              YESYES
YESYES   YES         YES          YES
YES  YES YES       YES               YES
YES    YESYES     YES                YES
YES      YESYE         YES         YES
YES          YES               YESYES
          """
]

YESWNO = [
    """
NO       NO   NONONO            NONO
 NO     NO    NO                      NO         NO
   NONO       NO                       NO
      NO           NONO                      NO
      NO           NO                 NO          NO
      NO           NO                    NO        NO
      NO           NONONO           NONO
"""
]

StartPic = [
    "https://files.catbox.moe/01qfx5.jpg",
    "https://files.catbox.moe/n3xguv.jpg",
    "https://files.catbox.moe/q62k7u.jpg",
    "https://files.catbox.moe/j9xeqj.jpg",
    "https://files.catbox.moe/57sgfw.jpg",
    "https://files.catbox.moe/55w9ys.jpg",
    "https://files.catbox.moe/9uttu2.jpg",
    "https://files.catbox.moe/3gjcjb.jpg",
    "https://files.catbox.moe/l9prwm.jpg",
    "https://files.catbox.moe/eea2ka.jpg",
    "https://files.catbox.moe/z6yd23.jpg",
    "https://files.catbox.moe/fsq2hg.jpg",
    "https://files.catbox.moe/2j80lj.jpg",
    "https://files.catbox.moe/qswx90.jpg",
]


birthday_wish = [
    "Wishing you a happy birthday filled with love and joy.",
    "Hope your birthday is as wonderful as you are.",
    "Happy birthday to someone who deserves a truly special day.",
    "May your birthday be full of surprises and delight.",
    "Wishing you a year filled with new adventures and accomplishments.",
    "May your birthday be as sweet as cake and as joyful as the celebration.",
    "Here's to a fabulous birthday and a year filled with blessings.",
    "Sending you lots of love and warm wishes on your special day.",
    "May your birthday be a time for reflection, relaxation, and joy.",
    "Cheers to another year of making unforgettable memories!",
    "May your birthday be filled with laughter, love, and good times.",
    "Wishing you a birthday that's just as amazing as you are.",
    "Here's to a year filled with love, happiness, and success.",
    "May your birthday be filled with all the love and blessings you deserve.",
    "Sending you warm wishes for a joyful and memorable birthday.",
    "Wishing you a birthday that's as wonderful as you are.",
    "May your birthday be a time to celebrate all the amazing things you've accomplished.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you lots of love, hugs, and birthday wishes.",
    "May your birthday be full of sunshine, laughter, and good times.",
    "Wishing you a year filled with happiness, success, and love.",
    "Here's to a fantastic birthday and an even better year ahead!",
    "May your birthday be a day filled with joy, love, and celebration.",
    "Sending you lots of love and warm wishes on your special day.",
    "Wishing you a birthday that's as bright and beautiful as you are.",
    "May your birthday be full of love, laughter, and happiness.",
    "Here's to a year filled with exciting adventures and new opportunities.",
    "Wishing you a birthday that's just as amazing as you are.",
    "May your birthday be a time to reflect on all the wonderful things in your life.",
    "Sending you lots of love, hugs, and birthday wishes from afar.",
    "Wishing you a year filled with love, laughter, and all your heart desires.",
    "May your birthday be a time to relax, unwind, and enjoy the company of loved ones.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you warm wishes for a wonderful and unforgettable birthday.",
    "Wishing you a birthday that's as special and unique as you are.",
    "May your birthday be a time to cherish all the special moments and memories you've created.",
    "Here's to a year filled with joy, laughter, and happiness.",
    "Wishing you a birthday that's just as amazing as you are.",
    "May your birthday be a time to celebrate your wonderful achievements and accomplishments.",
    "Sending you lots of love, hugs, and birthday wishes to make your day extra special.",
    "Wishing you a year filled with love, happiness, and all your heart's desires.",
    "May your birthday be a time to create new memories and cherish old ones.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you warm wishes for a fabulous and unforgettable birthday.",
    "Wishing you a birthday that's full of love, laughter, and happiness.",
    "May your birthday be a time to appreciate all the wonderful people in your life.",
    "Wishing you a birthday as amazing as you are, filled with joy and memories to last a lifetime.",
    "May your birthday be full of laughter and love, and your year be full of happiness and success.",
    "Happy birthday to someone who makes the world a better place, may all your wishes come true.",
    "Sending you warm birthday wishes and virtual hugs, can't wait to celebrate in person!",
    "May your birthday be as special as you are, surrounded by all the people who love you the most.",
    "Wishing you a day filled with laughter, and a year filled with new adventures and opportunities.",
    "Happy birthday to someone who's always there to brighten up my day, may your day be as bright as you are.",
    "Here's to a birthday that's just as awesome as you are, and a year filled with love and happiness.",
    "May your birthday be a time to reflect on all the wonderful memories you've made, and look forward to new ones.",
    "Wishing you a birthday that's full of surprises and excitement, and a year filled with new beginnings.",
    "Happy birthday to my favorite person in the world, may your day be as special as you are to me.",
    "Sending you the biggest birthday hugs and all my love, may your day be filled with joy and celebration.",
    "May your birthday be a time to celebrate all your accomplishments and be proud of all you've achieved.",
    "Wishing you a birthday that's as bright and beautiful as you are, filled with love and laughter.",
    "Happy birthday to a true gem, may your day be filled with joy, laughter, and all the things you love.",
    "Here's to a birthday that's full of happiness, excitement, and all the people who make your life special.",
    "May your birthday be a time to let loose and have fun, and your year be filled with growth and success.",
    "Wishing you a birthday that's full of all the things you love, and a year that's even better than the last.",
    "Happy birthday to someone who makes my life brighter, may your day be as amazing as you are.",
    "Sending you lots of love and virtual hugs on your special day, may your year be filled with blessings.",
    "May your birthday be a time to cherish all the people who make your life special, and celebrate the person you've become.",
    "Wishing you a birthday that's as unique and wonderful as you are, filled with love and laughter.",
    "Happy birthday to someone who's always been there for me, may your day be filled with joy and celebration.",
    "Here's to a birthday that's full of love, happiness, and all the things that bring you the most joy.",
    "May your birthday be a time to reflect on all the amazing things you've accomplished, and look forward to all that's to come.",
    "Wishing you a birthday that's full of surprises, happiness, and all the things that make you feel alive.",
    "Happy birthday to someone who brings a smile to my face every day, may your day be as wonderful as you are.",
    "Sending you all my love and warmest wishes on your special day, may your year be filled with love and happiness.",
    "May your birthday be a time to appreciate all the people who make your life special, and cherish all the memories you've created.",
    "Wishing you a birthday that's as beautiful as you are, filled with joy and celebration.",
]
